In [4]:
import pandas as pd
df = pd.read_csv('tokyo_POPS.csv')
df

,通番号,年度,番号,名称,位置,用途,敷地面積(m2),建築面積(m2),延べ面積(m2),駐車場等面積(m2),...,56道路,56隣地,58条,種別,人口,戸数,備考,address,lat,lng
0,1,1976,1,日野大久保団地,日野市日野6501,共同住宅,14855.35,3187.71,8859.36,0.00,...,NaN,NaN,NaN,NaN,NaN,184,NaN,東京都日野市日野6501,35.676946,139.408484
1,2,1976,2,第一勧業銀行本店,千代田区内幸町1-1-5,事務所,13484.43,7302.15,135013.82,13090.04,...,●,●,●,NaN,4000.0,NaN,中水,東京都千代田区内幸町1-1-5,35.670360,139.757954
2,3,1976,3,東京銀行,中央区日本橋本石町1,事務所,3123.18,2138.99,30443.66,5637.83,...,●,●,NaN,NaN,1060.0,NaN,NaN,東京都中央区日本橋本石町1,35.685166,139.771917
3,4,1976,4,ＡＴ計画,中央区築地5-2,事務所,21109.45,15933.82,145412.75,18792.08,...,●,●,NaN,NaN,8600.0,NaN,NaN,東京都中央区築地5-2,35.661597,139.769681
4,5,1977,1,虎ノ門三井ビル別館,港区赤坂葵町2-6-7,事務所,7938.11,4879.13,62157.22,5201.37,...,●,NaN,NaN,NaN,4000.0,NaN,中水,東京都港区赤坂葵町2-6-7,35.671205,139.735149
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
788,789,2024,5,(仮称)千代田区三番町６－５プロジェクト,千代田区三番町６-５外,共同住宅、飲食店、自動車車庫,2010.9,912.92,15179.13,4166.25,...,NaN,NaN,NaN,住,0.0,124,地域冷暖房、中水処理施設,東京都千代田区三番町６-５外,35.691648,139.745114
789,790,2024,6,(仮称)千代田区一番町計画,千代田区一番町１番３,共同住宅、自動車車庫,9259.31,4548.71,85274.99,37918.59,...,NaN,NaN,NaN,住,0.0,187,NaN,東京都千代田区一番町１番３,35.686756,139.743266
790,791,2025,1,（仮称）M計画,千代田区丸の内二丁目5番1、3番2,事務所、物販店舗、飲食店、集会場、自動車車庫,18937.72,13327.91,321351.04,45201.03,...,NaN,NaN,NaN,NaN,20540.0,0,NaN,東京都千代田区丸の内二丁目5番1、3番2,35.679907,139.763451
791,792,2025,2,(仮称)西五反田2丁目マンション計画,品川区西五反田2-8-2外,共同住宅、日用品の販売を主たる目的とする店舗,1554.23,684.19,20140.27,5874.50,...,NaN,NaN,NaN,住,0.0,202,NaN,東京都品川区西五反田2-8-2外,35.626785,139.721696
792,793,2025,3,(仮称)第７宮庭マンション建替計画,渋谷区千駄ヶ谷３丁目13－２外９筆,共同住宅、店舗、自動車車庫等,1179.08,582.17,11341.83,3957.29,...,NaN,NaN,NaN,共,0.0,110,NaN,東京都渋谷区千駄ヶ谷３丁目13－２外９筆,35.678043,139.705580

In [ ]:
df['address'] = '東京都' + df['位置']
df

In [5]:
import geocoder
import os
from dotenv import load_dotenv
load_dotenv()
os.environ["GEO_API_KEY"][:8] + "..."

'AIzaSyAl...'

In [9]:
rows = []
for address in df['address']:
    g = geocoder.google(address, key=os.environ.get('GEO_API_KEY'))
    if g.latlng:
        rows.append(g.latlng)
    else:
        rows.append([None, None])
df['lat'] = [r[0] for r in rows]
df['lng'] = [r[1] for r in rows]
df

Status code Unknown from https://maps.googleapis.com/maps/api/geocode/json: ERROR - HTTPSConnectionPool(host='maps.googleapis.com', port=443): Read timed out. (read timeout=5.0)

     通番号    年度  番号  ...               address        lat         lng
0      1  1976   1  ...          東京都日野市日野6501  35.676946  139.408484
1      2  1976   2  ...       東京都千代田区内幸町1-1-5  35.670360  139.757954
2      3  1976   3  ...         東京都中央区日本橋本石町1  35.685166  139.771917
3      4  1976   4  ...           東京都中央区築地5-2  35.661597  139.769681
4      5  1977   1  ...        東京都港区赤坂葵町2-6-7  35.671205  139.735149
..   ...   ...  ..  ...                   ...        ...         ...
788  789  2024   5  ...        東京都千代田区三番町６-５外  35.691648  139.745114
789  790  2024   6  ...         東京都千代田区一番町１番３  35.686756  139.743266
790  791  2025   1  ...  東京都千代田区丸の内二丁目5番1、3番2  35.679907  139.763451
791  792  2025   2  ...      東京都品川区西五反田2-8-2外  35.626785  139.721696
792  793  2025   3  ...  東京都渋谷区千駄ヶ谷３丁目13－２外９筆  35.678043  139.705580

[793 rows x 28 columns]

In [ ]:
rows = []
for i,address in enumerate(df['address'], start=1):
    try:
        print(f'{i}/{len(df)}{address}')
        g = geocoder.google(address, key=os.environ.get('GEO_API_KEY'), timeout=30)
        if g.latlng:
            rows.append(g.latlng)
        else:
            rows.append([None, None])
    except Exception as e:
        print('error', address)
        rows.append([None, None])

df['lat'] = [r[0] for r in rows]
df['lng'] = [r[1] for r in rows]
df

In [17]:
len(df['lng'].unique())
df.to_csv('tokyo_pops.csv', index=False)